---
abstract: 'a simple PSGI/Plack HTTP server which uses threads'
author:
  - 'Piotr Roszatycki <dexter@cpan.org>'
build_requires:
  HTTP::Tiny: 0
  Test::More: 0.88
  Test::TCP: 0.15
dynamic_config: 1
generated_by: 'Module::Build version 0.4203, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Thrall
provides:
  Plack::Handler::Thrall:
    file: lib/Plack/Handler/Thrall.pm
    version: 0.0201
  Thrall:
    file: lib/Thrall.pm
    version: 0.0201
  Thrall::Server:
    file: lib/Thrall/Server.pm
    version: 0.0201
requires:
  Plack: 0.992
  perl: 5.008001
  threads: 1.73
resources:
  bugtracker: http://github.com/dex4er/Thrall/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/dex4er/Thrall
version: 0.0201
